apiVersion: apps/v1
kind: Deployment
metadata:
  name: safespring-docs-deployment
spec:
  selector:
    matchLabels:
      app: safespring-docs
  replicas: 3
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: safespring-docs
    spec:
      containers:
      - name: safespring-docs
        image: registry.example.safespring.com/safespring/docs:%%TAG%%
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: safespring-docs-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
      targetPort: 80
      name: http
  selector:
    app: safespring-docs
